php/backend/controllers/DeleteController.php
<?php

namespace backend\controllers;


use common\models\type\Slider;
use common\models\type\Tag;
use yii\web\Controller;
use Yii;
use yii\web\NotFoundHttpException;

class DeleteController extends Controller {

    function actionTag($id) {
        if (($model = Tag::findOne($id)) !== null) {
                $model->delete();
                return $this->redirect(['/admin/tags']);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    function actionSlider($id) {
        if (($model = Slider::findOne($id)) !== null) {
            @unlink(Yii::getAlias('@uploadsroot/slider/'.$model->picture));
            @unlink(Yii::getAlias('@uploadsroot/slider/'.$model->background));
            $model->delete();
            return $this->redirect(['/admin/slider']);
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

php/backend/controllers/EditController.php
<?php
/**
 * Created by PhpStorm.
 * User: zachot
 * Date: 02.08.15
 * Time: 1:25
 */

namespace backend\controllers;


use backend\models\edit\EditPartner;
use backend\models\edit\EditProject;
use backend\models\edit\EditTeammate;

use common\models\type\Slider;
use common\models\type\Tag;
use yii\web\Controller;
use Yii;
use yii\web\NotFoundHttpException;

class EditController extends Controller {

	function actionProject() {
		$id = \Yii::$app->request->get('id');
		$model = new EditProject();
		if ($id && is_numeric($id))
			$model->loadProject($id);

		if (\Yii::$app->request->isPost)
			if (!$model->go()) {
				if ($model->hasErrors('empty')) {
					$model->clearErrors('empty');
					return $this->redirect('@web/edit/project?id=' . $model->getId(), 302);
				}
			}

		return $this->render('project', ['model' => $model]);
	}

	function actionTeammate() {

		$id = \Yii::$app->request->get('id');

		$model = new EditTeammate();
		if ($id && is_numeric($id))
			$model->loadTeammate($id);

		if (\Yii::$app->request->isPost)
			if (!$model->go()) {
				if ($model->hasErrors('empty')) {
					$model->clearErrors('empty');
					return $this->redirect('@web/edit/teammate?id=' . $model->getId(), 302);
				}
			}

		return $this->render('teammate', ['model' => $model]);
	}

    function actionPartner() {

        $id = \Yii::$app->request->get('id');

        $model = new EditPartner();
        if ($id && is_numeric($id))
            $model->loadPartner($id);

        if (\Yii::$app->request->isPost)
            if (!$model->go()) {
                if ($model->hasErrors('empty')) {
                    $model->clearErrors('empty');
                    return $this->redirect('@web/edit/partner?id=' . $model->getId(), 302);
                }
            }

        return $this->render('partner', ['model' => $model]);
    }

    function actionTag($id) {
        if (($model = Tag::findOne($id)) !== null) {
            if ($model->load(Yii::$app->request->post()) && $model->save()) {
                return $this->redirect(['/admin/tags']);
            } else {
                return $this->render('tag', [
                    'model' => $model,
                ]);
            }
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }

    function actionSlider($id) {
        if ((($model = Slider::findOne($id)) !== null) || $id == 0) {
            if ($id == 0)  {
                $model = new Slider();
                $model->scenario = 'create';
            }
            if ($model->load(Yii::$app->request->post()) && $model->go()) {
                return $this->redirect(['/admin/slider']);
            } else {
                return $this->render('slider', [
                    'model' => $model,
                ]);
            }
        } else {
            throw new NotFoundHttpException('Элемент не найден');
        }
    }
}

php/backend/views/admin/index.php
<?php


/**
 * @var $this \yii\web\View
 */

$this->registerJsFile('@web/assets/angular.min.js', ['position' => $this::POS_END]);
$this->registerJsFile('@web/assets/ngDraggable.js', ['position' => $this::POS_END]);
$this->registerJsFile('@web/js/admin-angular.js', ['position' => $this::POS_END]);
?>
<div ng-app="studio">

	<input type="hidden" name="_csrf" value="<?= Yii::$app->request->getCsrfToken() ?>"/>


	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">Главная</h1>
		</div>
	</div>
	<div class="row" ng-controller="Portfolio">


		<div class="col-xs-6">
			<h2>
				<a href="#" ng-click="hidePosition()">Портфолио</a>
			</h2>
		</div>
		<div class="col-xs-6">
			<h2 class="text-right"><a href="#" ng-click="showPosition()">Расположение</a></h2>
		</div>
		<div class="col-xs-12" ng-hide="position">
			<div class="row">
				<div style="min-height: 370px;" class="col-xs-{{project.size}}"
						 ng-repeat="project in json.portfolio  track by $index">

					<div style="background: rgba(0,0,0,.1); padding: 3px;">

						<div class="row">
							<div class="form-group col-xs-7">
								<label class="control-label" for="">Заголовок</label>
								<input type="text" ng-model="project.title" class="form-control">
							</div>
							<div class="form-group col-xs-5">
								<label class="control-label" for="">Мини текст</label>
								<input type="text" ng-model="project.description" class="form-control">
							</div>
						</div>
						<div class="row">

							<div class="form-group col-xs-8">
								<label class="control-label" for="">Проект</label>
								<select ng-model="project.slug" class="form-control">
									<option value="{{pr.slug}}" ng-selected="{{project.slug == pr.slug}}" ng-repeat="pr in json.projects">
										{{pr.title}}
									</option>
								</select>
							</div>
							<div class="form-group col-xs-4">
								<label class="control-label" for="">Размер</label>
								<select ng-model="project.size" class="form-control" convert-to-number>
									<option value="4">4</option>
									<option value="8">8</option>
								</select>
							</div>
						</div>
						<div class="row">

							<div class="col-xs-12">
								<label class="control-label" for=""> Изображение</label>
							</div>
							<div class="col-xs-4">
								<div class="form-group text-center">
									<img ng-src="{{project.image_url}}" class="img-responsive" alt="" style="height:50px;">

									<input type="hidden" ng-model="project.image">
								</div>
							</div>
							<div class="col-xs-8">
								<input type="file" class="upload-image" data-name="image" data-index="{{$index}}" name="Upload[image]">
							</div>
						</div>
                        <div class="row">
                            <div class="col-xs-12">
                                <label class="control-label" for="">Теги</label>
                                <select ng-model="project.tag_slug" class="form-control">
                                    <option value="{{tag.slug}}" ng-selected="{{tag.slug == project.tag_slug}}" ng-repeat="tag in json.tags">{{tag.name}}</option>
                                </select>
                            </div>
                        </div>
						<button ng-click="remove($index)" class="btn btn-sm btn-danger">Удалить</button>
					</div>

				</div>

				<div class="col-xs-{{new_portfolio.size}}" style="min-height: 300px;">

					<div style="background: rgba(0,0,0,.2); padding: 3px;">
						<div class="row">
							<div class="form-group col-xs-7">
								<label class="control-label" for="">Заголовок</label>
								<input type="text" ng-model="new_portfolio.title" class="form-control">
							</div>
							<div class="form-group col-xs-5">
								<label class="control-label" for="">Мини текст</label>
								<input type="text" ng-model="new_portfolio.description" class="form-control">
							</div>
						</div>

						<div class="row">
							<div class="form-group col-xs-8">
								<label class="control-label" for="">Проект</label>
								<select ng-model="new_portfolio.slug" class="form-control">
									<option value="{{pr.slug}}" ng-repeat="pr in json.projects">{{pr.title}}</option>
								</select>
							</div>
							<div class="form-group col-xs-4">
								<label class="control-label" for="">Размер</label>
								<select ng-model="new_portfolio.size" class="form-control">
									<option value="4">4</option>
									<option value="8">8</option>
								</select>
							</div>
						</div>

						<div class="row">
							<div class="col-xs-12">
								<label class="control-label" for=""> Изображение</label>
							</div>
							<div class="col-xs-4">
								<div class="form-group">
									<img ng-src="{{new_portfolio.image_url}}" class="img-responsive" alt="">

									<input type="hidden" ng-model="new_portfolio.image">
								</div>
							</div>
							<div class="col-xs-8">
								<input type="file" class="upload-image" data-name="image" name="Upload[image]">
							</div>
						</div>
                        <div class="row">
                            <div class="col-xs-12">
                                <label class="control-label" for="">Теги</label>
                                <select ng-model="new_portfolio.tag" class="form-control">
                                    <option value="{{tag}}" ng-repeat="tag in json.tags">{{tag}}</option>
                                </select>
                            </div>
                        </div>
						<button ng-click="addNew()" class="btn btn-sm btn-primary">Добавить</button>
					</div>
				</div>
			</div>
		</div>

		<div class="col-xs-12" ng-show="position">

			<div class="row">
				<div style="min-height: 200px;position: relative" class="col-xs-{{project.size}}"
						 ng-repeat="project in json.portfolio  track by $index"
						 ng-drag="true" ng-drag-data="project"
						 ng-drag-success="onDragComplete($data,$event)"

						 ng-drop="true"
						 ng-drop-success="onDropComplete($index, $data,$event)">

					<div
						style="background: rgba(0,0,0,.1) url('{{project.image_url}}') center no-repeat; background-size: cover; height: 170px; margin-top: 15px; padding: 3px;">
						<div class="row">
							<div class="col-xs-8">

								<h2 style="margin-left: 15px; color: white; text-shadow: 1px 1px 2px rgba(0,0,0,.4);">
									{{project.title}}</h2>
							</div>
						</div>
					</div>

				</div>
			</div>

		</div>
	</div>
</div>

php/backend/views/admin/login.php
<?php
/**
 * @var $model \backend\models\Login
 */
?>
<div class="container">
	<div class="row">
		<div class="col-md-4 col-md-offset-4">
			<div class="login-panel panel panel-default">
				<div class="panel-heading">
					<h3 class="panel-title">Please Sign In</h3>
				</div>
				<div class="panel-body">
					<?php $form = \yii\widgets\ActiveForm::begin(['options' => ['class' => 'form-login form']]); ?>

					<?php if ($model->hasErrors()) { ?>
						<div class="alert alert-danger">Ошибка</div>
					<?php } ?>

					<fieldset>

						<?php /*
						$user = new \backend\models\User();
						$user->setAttribute('login', 'studio-admin');
						$user->setAttribute('password', Yii::$app->getSecurity()->generatePasswordHash('a$grLps1-4ivn3'));
						$user->setAttribute('token', sha1('a$grLps1-4ivn3'));

						$user->save();
						*/ ?>



						<?= $form->field($model, 'login')
							->textInput(
								['placeholder' => 'Логин',
									'class' => 'form-control']
							)->label('Логин') ?>


						<?= $form->field($model, 'password')
							->passwordInput(
								['placeholder' => 'Пароль',
									'class' => 'form-control']
							)->label('Пароль') ?>


						<!-- Change this to a button or input when using this as a form -->
						<button class="btn btn-lg btn-success btn-block">Login</button>
					</fieldset>

					<?php \yii\widgets\ActiveForm::end(); ?>
				</div>
			</div>
		</div>
	</div>
</div>

php/backend/views/admin/partners.php
<?php
/**
 * @var $partners \backend\models\type\Partner[]
 */


$this->registerJsFile('@web/assets/angular.min.js', ['position' => $this::POS_END]);
$this->registerJsFile('@web/assets/ngDraggable.js', ['position' => $this::POS_END]);
$this->registerJsFile('@web/js/admin-angular.js', ['position' => $this::POS_END]);


?>
<div>
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">Партнеры <a class="btn btn-sm" href="<?= \yii\helpers\Url::to('@web/edit/partner') ?>">+<i
						class="fa fa-user"></i> добавить</a>
			</h1>
		</div>
	</div>

	<div class="panel panel-default">

		<div class="panel-body">
			<table class="table table-striped table-bordered table-hover data-table">
				<thead>
				<tr>
					<th>Фото</th>
					<th>Имя</th>
					<th>Меню</th>
				</tr>
				</thead>
				<tfoot>
				<tr>
					<td colspan="3"><a class="btn btn-primary" href="<?= \yii\helpers\Url::to('@web/edit/partner?id=0') ?>">Добавить</a>
					</td>
				</tr>
				</tfoot>
				<tbody>
				<?php foreach ($partners as $partner) { ?>
					<tr>
						<td style="width: 100px; text-align: center;"><img class="img-responsive" src="<?= $partner->getLogoUrl() ?>"></td>
						<td>
							<h4><?= $partner->getAttribute('name') ?></h4>

						</td>
						<td>
							<div>
								<label for="">На странице</label>
								<a class="js-toggle"
									 href="<?= \yii\helpers\Url::to("@web/json/toggle-partner-visible?id=" . $partner->getAttribute('id')) ?>"
									 data-toggle-inner="<?= ($partner->getAttribute('visible')) ? "Скрыт -> Показать" : "Виден -> Скрыть" ?>"
									><?= ($partner->getAttribute('visible')) ? "Виден -> Скрыть" : "Скрыт -> Показать" ?></a>
							</div>

							<div>
								<div>Изменить</div>
								<a class="btn btn-sm btn-primary" href="<?= \yii\helpers\Url::to('@web/edit/partner?id=' . $partner->getAttribute('id')) ?>">Редактировать</a>

							</div>

						</td>
					</tr>
				<?php } ?>

				</tbody>
			</table>
		</div>
	</div>
</div>

php/backend/views/admin/projects.php
<?php
/**
 * @var $projects \backend\models\type\Project[];
 */

use backend\models\type\Project;
?>

<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Проекты</h1>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-body">
		<table class="table table-striped table-bordered table-hover data-table">
			<thead>
			<tr>
				<th>Картинка</th>
				<th>Заголовок</th>
				<th>Комнаты</th>
			</tr>
			</thead>
			<tfoot>
			<tr>
				<td colspan="2"><a class="btn btn-primary"
													 href="<?= \yii\helpers\Url::to('@web/edit/project?id=0') ?>">Добавить</a></td>
			</tr>
			</tfoot>
			<tbody>
			<?php $projects = Project::find()->orderBy(['id' => SORT_DESC])->all() ?>
			<?php foreach ($projects as $project) { ?>
				<tr>
					<td style="width: 200px;"><img style="width: 200px;" src="<?= $project->getThumbnailAttachmentUrl() ?>"></td>
					<td>
						<?= $project->getAttribute('title') ?>
						<div>
							<a href="<?= \yii\helpers\Url::to('@web/edit/project?id=' . $project->getAttribute('id')) ?>">Редактировать</a>
							<a class="text-danger js-delete"
								 href="<?= \yii\helpers\Url::to('@web/json/toggle-project-delete?id=' . $project->getAttribute('id')) ?>">Удалить</a>
						</div>
					</td>
					<td>
						<ul style="font-size: 10px;">
							<?php
							$rooms = $project->getRooms();
							foreach ($rooms as $room) {
								echo "<li>" . $room->getAttribute('title') . "</li>";
							}
							?>
						</ul>
					</td>
				</tr>
			<?php } ?>

			</tbody>
		</table>
	</div>
</div>

php/backend/views/admin/report.php
<?php
/**
 * @var $reports \backend\models\type\Report[]
 */
?>

<div class="row">
	<div class="col-lg-12">
		<h1 class="page-header">Сообщения с сайта</h1>
	</div>
</div>

<div class="panel panel-default">
	<div class="panel-body">
		<table class="table table-striped table-bordered table-hover data-table">
			<thead>
			<tr>
				<th>От кого</th>
				<th>Что пишет</th>
			</tr>
			</thead>

			<tbody>

			<?php foreach ($reports as $report) { ?>
				<tr>
					<td>
						<div><h4><?= $report->getAttribute('user_name') ?></h4></div>
						<div><span><?= $report->getAttribute('user_phone') ?></span></div>
						<div><span><a
									href="mailto:<?= $report->getAttribute('user_email') ?>"><?= $report->getAttribute('user_email') ?></a></span>
						</div>
					</td>
					<td>
						<?php
						$project = $report->getProject();
						if ($project) {
							?>
							<div style="margin-bottom: 5px; font-size: 10px;">
								В проекте <a target="_blank"
														 href="<?= \yii\helpers\Url::to('@webUrl/' . $project->getAttribute('slug')) ?>"><?= $project->getAttribute('title') ?></a>
							</div>
							<?php
						}
						?>
						<div style="font-style: italic;">
							<?= $report->getAttribute('user_text') ?>
						</div>
					</td>
				</tr>
			<?php } ?>

			</tbody>
		</table>
	</div>
</div>

php/backend/views/admin/slider.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\data\ActiveDataProvider;
use backend\models\type\Slider;

/* @var $this yii\web\View */

$this->title = 'Слайдер';
$this->params['breadcrumbs'][] = $this->title;
$dataProvider = new ActiveDataProvider([
		'query' => Slider::find(),
		'sort'=> ['defaultOrder' => ['position'=>SORT_ASC]]
]);
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        <div class="tag-index">

            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    'id',
                    'text:ntext',
                    'link:ntext',
                    [
                        'class' => 'yii\grid\DataColumn',
                        'attribute' => 'picture',
                        'value' => function ($model, $key, $index, $column)
                            {
                                return "<img src='".Yii::getAlias('@uploads/slider/'.$model->picture)."' width='300px'/>";
                            },
                        'format' => 'raw',
                    ],
                    [
                        'class' => 'yii\grid\DataColumn',
                        'attribute' => 'background',
                        'value' => function ($model, $key, $index, $column)
                            {
                                return "<img src='".Yii::getAlias('@uploads/slider/'.$model->background)."' width='300px'/>";
                            },
                        'format' => 'raw',
                    ],
                    [
                        'class' => 'yii\grid\DataColumn',
                        'value' => function ($model, $key, $index, $column)
                            {
                            	$sliders = \backend\models\type\Slider::find()->orderBy('position')->all();
                            	$moveUp = \yii\helpers\Url::to('@web/json/move-slider-up?id=' . $model->getAttribute('id') . '&pos=' . $model->getAttribute('position'));
                            	$disableUpClass = $model->getAttribute('position') == 0 ? "disabled" : "";
                            	$moveDown = \yii\helpers\Url::to('@web/json/move-slider-down?id=' . $model->getAttribute('id') . '&pos=' . $model->getAttribute('position'));
                            	$disableDownClass = $model->getAttribute('position') == (count($sliders)-1) ? "disabled" : "";
                                return "<a class='btn btn-sm btn-primary' href='".\yii\helpers\Url::to(['/edit/slider', 'id' => $model->id])."'>Редактировать</a>"." ".
                                "<a class='btn btn-sm btn-danger' href='".\yii\helpers\Url::to(['/delete/slider', 'id' => $model->id])."'>Удалить</a>"."<br/>".
                        		"<a class='btn btn-sm btn-default ".$disableUpClass."' href='".$moveUp."'>Вверх</a>"."<br/>".
                        		"<a class='btn btn-sm btn-warning ".$disableDownClass."' href='".$moveDown."'>Вниз</a>";
                            },
                        'format' => 'raw',
                    ],
                ],
            ]); ?>
        </div>
        <div>
            <a class="btn btn-primary"
               href="<?= \yii\helpers\Url::to('@web/edit/slider?id=0') ?>">Добавить</a>
        </div>
    </div>
</div>

php/backend/views/admin/tags.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;

/* @var $this yii\web\View */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Теги';
$this->params['breadcrumbs'][] = $this->title;
?>
<div class="row">
    <div class="col-lg-12">
        <h1 class="page-header"><?= Html::encode($this->title) ?></h1>
    </div>
</div>
<div class="panel panel-default">
    <div class="panel-body">
        <div class="tag-index">

            <?= GridView::widget([
                'dataProvider' => $dataProvider,
                'columns' => [
                    ['class' => 'yii\grid\SerialColumn'],

                    'id',
                    'name:ntext',
                    'slug:ntext',
                    [
                        'class' => 'yii\grid\DataColumn',
                        'value' => function ($model, $key, $index, $column)
                            {
                                return "<a class='btn btn-sm btn-primary' href='".\yii\helpers\Url::to(['/edit/tag', 'id' => $model->id])."'>Редактировать</a>"." ".
                                "<a class='btn btn-sm btn-danger' href='".\yii\helpers\Url::to(['/delete/tag', 'id' => $model->id])."'>Удалить</a>";
                            },
                        'format' => 'raw',
                    ],
                ],
            ]); ?>
        </div>
    </div>
</div>

php/backend/views/admin/team.php
<?php
/**
 * @var $team \backend\models\type\Teammate[]
 */


$this->registerJsFile('@web/assets/angular.min.js', ['position' => $this::POS_END]);
$this->registerJsFile('@web/assets/ngDraggable.js', ['position' => $this::POS_END]);
$this->registerJsFile('@web/js/admin-angular.js', ['position' => $this::POS_END]);


?>
<div>
	<div class="row">
		<div class="col-lg-12">
			<h1 class="page-header">Команда <a class="btn btn-sm" href="<?= \yii\helpers\Url::to('@web/edit/teammate') ?>">+<i
						class="fa fa-user"></i> добавить</a>
			</h1>
		</div>
	</div>

	<div class="panel panel-default">

		<div class="panel-body">
			<table class="table table-striped table-bordered table-hover data-table">
				<thead>
				<tr>
					<th>Фото</th>
					<th>Имя</th>
					<th>Меню</th>
				</tr>
				</thead>
				<tfoot>
				<tr>
					<td colspan="3"><a class="btn btn-primary" href="<?= \yii\helpers\Url::to('@web/edit/teammate?id=0') ?>">Добавить</a>
					</td>
				</tr>
				</tfoot>
				<tbody>
				<?php 
				$team = \backend\models\type\Teammate::find()->orderBy('position')->all();
				foreach ($team as $teammate) { 
				?>
					<tr>
						<td style="width: 100px; text-align: center;"><img class="img-responsive"
																															 src="<?= $teammate->getPhotoUrl() ?>"></td>
						<td>
							<h4><?= $teammate->getAttribute('name') ?></h4>

							<p><?= $teammate->getAttribute('profession') ?></p>

						</td>
						<td>
							<div>
								<label for="">На главной</label>
								<a class="js-toggle"
									 href="<?= \yii\helpers\Url::to("@web/json/toggle-person-main?id=" . $teammate->getAttribute('id')) ?>"
									 data-toggle-inner="<?= ($teammate->getAttribute('main')) ? "Скрыт -> Показать" : "Виден -> Скрыть" ?>"
									><?= ($teammate->getAttribute('main')) ? "Виден -> Скрыть" : "Скрыт -> Показать" ?></a>
							</div>
							<div>
								<label for="">Бывший сотрудник</label>
								<a class="js-toggle"
									 href="<?= \yii\helpers\Url::to("@web/json/toggle-person-past?id=" . $teammate->getAttribute('id')) ?>"
									 data-toggle-inner="<?= ($teammate->getAttribute('past')) ? "Сделать бывшим" : "Сделать настоящим" ?>"
									><?= ($teammate->getAttribute('past')) ? "Сделать настоящим" : "Сделать бывшим" ?></a>
							</div>

							<div>
								<div>Изменить</div>
								<a class="btn btn-sm btn-primary" href="<?= \yii\helpers\Url::to('@web/edit/teammate?id=' . $teammate->getAttribute('id')) ?>">Редактировать</a>
								
							</div>
							<div>
								<div>Позиция</div>
								<?php $moveUp = \yii\helpers\Url::to('@web/json/move-teammate-up?id=' . $teammate->getAttribute('id') . '&pos=' . $teammate->getAttribute('position')) ?>
								<?php $moveDown = \yii\helpers\Url::to('@web/json/move-teammate-down?id=' . $teammate->getAttribute('id') . '&pos=' . $teammate->getAttribute('position')) ?>
								<a class="btn btn-sm btn-default <?= ($teammate->getAttribute('position') == 1) ? "disabled" : "" ?>" href="<?= $moveUp ?>">Вверх</a>
								<a class="btn btn-sm btn-warning <?= ($teammate->getAttribute('position') == count($team)) ? "disabled" : "" ?>" href="<?= $moveDown?>">Вниз</a>
							</div>

						</td>
					</tr>
				<?php } ?>

				</tbody>
			</table>
		</div>
	</div>
</div>